// Run after npm run build; requires Playwright (local install or NODE_PATH).
const { chromium } = require('playwright')
const http = require('node:http')
const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

async function main() {
  const root = path.resolve(__dirname, '../dist/renderer')
  const server = http.createServer((req, res) => {
    const file = path.resolve(root, '.' + (req.url === '/' ? '/index.html' : req.url.split('?')[0]))
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) { res.writeHead(404).end(); return }
    res.setHeader('Content-Type', file.endsWith('.js') ? 'application/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html')
    res.end(fs.readFileSync(file))
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  let browser
  try {
    browser = await chromium.launch({ channel: 'msedge', headless: true })
    const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } })
    const errors = []
    const taskLogs = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/api/**', route => {
      const url = route.request().url()
      const body = url.includes('/health') ? { status: 'ok' } : url.includes('/tasks') ? (taskLogs.length ? [{ task_id: 'scroll-test', task_name: 'Scroll', status: 'running', log_lines: taskLogs, output_files: [], progress: 0, current: 0, total: 1 }] : [])
        : url.includes('/scan') ? { files: ['music.wav'], count: 1 }
        : url.includes('/probe') ? { audio_duration: 25, source_duration: 3 } : {}
      return route.fulfill({ json: body })
    })
    await page.goto(`http://127.0.0.1:${server.address().port}`)
    await page.getByRole('button', { name: '简易教程', exact: true }).click()
    assert.equal(await page.getByRole('textbox', { name: '码率', exact: true }).inputValue(), '8000k')
    assert.equal(await page.getByRole('dialog', { name: '简易教程' }).isVisible(), true)
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog', { name: '简易教程' }).isVisible(), false)
    assert.equal(await page.getByRole('button', { name: '简易教程', exact: true }).evaluate(el => el === document.activeElement), true)
    await page.getByRole('button', { name: 'Light', exact: true }).click()
    await page.getByRole('checkbox', { name: '普通 Body 按原素材时长', exact: true }).click()
    assert.equal(await page.getByRole('textbox', { name: '后段', exact: true }).isDisabled(), true)
    assert.equal(await page.getByRole('textbox', { name: 'Body', exact: true }).isDisabled(), true)
    await page.getByRole('checkbox', { name: '普通 Body 按原素材时长', exact: true }).click()
    assert.equal(await page.getByRole('textbox', { name: '后段', exact: true }).isEnabled(), true)
    await page.getByRole('button', { name: '分组', exact: true }).click()
    await page.getByRole('checkbox', { name: 'Body 1 按原素材时长', exact: true }).click()
    assert.equal(await page.getByRole('spinbutton', { name: 'Body 1 每段时长', exact: true }).isDisabled(), true)
    assert.equal(await page.getByRole('spinbutton', { name: 'Body 2 每段时长', exact: true }).isEnabled(), true)
    await page.getByRole('checkbox', { name: 'Body 1 按原素材时长', exact: true }).click()
    const colors = await page.locator('input:not([type=checkbox])').evaluateAll(inputs => inputs.map(el => {
      const css = getComputedStyle(el); return { bg: css.backgroundColor, text: css.color }
    }))
    assert(colors.length > 10)
    assert(colors.every(c => c.bg === 'rgb(255, 255, 255)' && c.text !== 'rgb(255, 255, 255)'), JSON.stringify(colors))
    await page.getByRole('button', { name: 'BGM 配乐说明' }).click()
    const help = page.getByRole('dialog', { name: 'BGM 配乐说明' })
    assert.equal(await help.isVisible(), true)
    const bounds = await help.boundingBox()
    assert(bounds.x >= 0 && bounds.x + bounds.width <= 1440 && bounds.y + bounds.height <= 1080)
    await page.screenshot({ path: path.resolve(__dirname, '../dist/ui-light-help.png') })
    await page.mouse.click(1435, 1075)
    assert.equal(await help.isVisible(), false)
    assert.equal(await page.getByRole('button', { name: '按 BGM 时长', exact: true }).isEnabled(), true)
    await page.getByRole('button', { name: '按 BGM 时长', exact: true }).click()
    await page.getByText('请先选择 BGM，再开启按 BGM 时长', { exact: true }).waitFor()
    assert.equal(await page.getByRole('textbox', { name: 'BGM 路径', exact: true }).evaluate(el => el === document.activeElement), true)
    assert.equal(await page.getByText('可选', { exact: true }).count(), 4)
    assert(Math.abs(await page.locator('.feature-help-glyph').first().evaluate(el => parseFloat(getComputedStyle(el).width)) - 9) < .1)
    await page.getByRole('textbox', { name: 'BGM 路径', exact: true }).fill('music')
    await page.getByRole('button', { name: '按 BGM 时长', exact: true }).click()
    await page.getByText('预计成片 25.000–25.000s', { exact: true }).waitFor()
    await page.getByRole('textbox', { name: 'BGM 路径', exact: true }).fill('')
    assert.equal(await page.getByRole('button', { name: '按片段数量', exact: true }).getAttribute('aria-pressed'), 'true')
    await page.getByText('未选择 BGM，已恢复按片段数量生成', { exact: true }).waitFor()
    await page.getByRole('button', { name: '简易教程', exact: true }).click()
    await page.screenshot({ path: path.resolve(__dirname, '../dist/ui-light-tutorial.png') })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Dark', exact: true }).click()
    await page.getByText('建议打开', { exact: true }).waitFor()
    taskLogs.push(...Array.from({ length: 150 }, (_, i) => `回归日志 ${i}`))
    await page.getByText('回归日志 149', { exact: true }).waitFor()
    const logPanel = page.locator('[aria-label="运行日志"]')
    const atBottom = () => logPanel.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop < 10)
    assert.equal(await atBottom(), true)
    await logPanel.evaluate(el => { el.scrollTop = 80; el.dispatchEvent(new Event('scroll', { bubbles: true })) })
    taskLogs.push('新增日志不抢滚动位置')
    await page.getByText('新增日志不抢滚动位置', { exact: true }).waitFor({ state: 'attached' })
    assert(Math.abs(await logPanel.evaluate(el => el.scrollTop) - 80) < 2)
    await page.getByRole('button', { name: /^产出/ }).click()
    await page.getByRole('button', { name: /^日志/ }).click()
    assert(Math.abs(await logPanel.evaluate(el => el.scrollTop) - 80) < 2)
    await logPanel.evaluate(el => { el.scrollTop = el.scrollHeight; el.dispatchEvent(new Event('scroll', { bubbles: true })) })
    taskLogs.push('恢复底部跟随')
    await page.getByText('恢复底部跟随', { exact: true }).waitFor()
    assert.equal(await atBottom(), true)
    await page.screenshot({ path: path.resolve(__dirname, '../dist/ui-dark.png') })
    assert.deepEqual(errors, [])
    console.log('UI smoke passed: themes, grouped inputs, help placement, tutorial, Escape, outside click, focus restoration, BGM mode and duration.')
  } finally {
    await browser?.close()
    await new Promise(resolve => server.close(resolve))
  }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
